server:
  port: ${PORT:8000}
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
    key-store-type: JKS
    key-store-provider: SUN
    key-alias: tomcat
  servlet:
    jsp:
      init-parameters:
        mappedfile: false
    session:
      timeout: 500
spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: { host }
    port: { port }
    username: {email}
    password: { password }
    protocol: smtp
    properties.mail.smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls.enable: true
      starttls.required: true
      ssl.trust: { ssl trust server }
  flyway:
    schemas: migrations
    locations: classpath:migration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10000MB
      max-request-size: 10000MB
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: scano
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/scano?createDatabaseIfNotExist=true
    username: { pguser }
    password: { pgpass }
    driver-class-name: org.postgresql.Driver
  #  liquibase:
  #    change-log: classpath:/db/changelog/db.changelog-master.xml
  devtools:
    restart:
      enabled: true
  worker:
    scheme: https
    host: ${WORKER_HOST}
    port: 443

  jpa:
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        hbm2ddl:
          auto: update
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
Encryption:
  password: encryptpassword_51Lg4CQIfHgEomwEqUUX8sh9cOx9EA41O2GH27It4WnucEVRnFMKdE05PP7lphKCfTDmVuOBgfeZYz09LomfOR1qi00apEC7kmA
  salt: encryptsalt_51Lg4CQIfHgEomwEqUUX8sh9cOx9EA41O2GH27It4WnucEVRnFMKdE05PP7lphKCfTDmVuOBgfeZYz09LomfOR1qi00apEC7kmA

stripe:
  key:
    secret: { secret }
    public: { public }

auth:
  jwtExpirationMs: 86400000
  jwtRefreshExpirationMs: 86400000
  secret: secretauth2002
  header: Authorization
logging:
  level:
    org:
      hibernate: ERROR
  file:
    name: {workspacedir}/${spring.application.name}.log